// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated from ..\mus\instrumentos.asm
// Generated by wyztrackerparser v0.1 20200515

#asm
     
    ; Tabla de instrumentos 
    .TABLA_PAUTAS
        defw PAUTA_0 
     
    ; Tabla de efectos 
    .TABLA_SONIDOS
        defw 0 
     
    ;Pautas (instrumentos) 
    ;Instrumento 'Piano' 
    .PAUTA_0
        defb 15,17,13,0,12,0,11,0,129 
     
    ;Efectos 
     
    ;Frecuencias para las notas 
#endasm
